from __future__ import annotations

"""
Automatic engine builder for generated CIF packages.

Unlike the previous case-study configuration, this builder discovers the
available generated modules through factory.py and derives a safe execution
order from the CIF bindings whenever possible.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from pipeline.scenario_inputs import EventTraceItem
from pipeline.binding_resolver import resolve_bindings_from_file
from pipeline.core.binding_applier import apply_cif_bindings, apply_input_bindings
from pipeline.core.generic_engine import GenericSimulationEngine
from pipeline.core.module_loader import load_generated_factory


@dataclass
class AutoBuildResult:
    engine: GenericSimulationEngine
    factory: Any
    input_modules: list[str] = field(default_factory=list)
    dynamic_templates: list[str] = field(default_factory=list)
    dynamic_modules: list[str] = field(default_factory=list)
    execution_order: list[str] = field(default_factory=list)


def _accepted_input_kwargs(limit: int | None, hours: int, input_values: dict[str, Any]) -> dict[str, Any]:
    # Generated input modules accept **input_series, so we can pass all values.
    kwargs = dict(input_values)
    kwargs["limit"] = limit
    kwargs["hours"] = hours
    return kwargs


def _topological_module_order(module_names: list[str], bindings: Iterable[Any]) -> list[str]:
    """
    Order module instances according to source -> target dependencies.

    This is needed whenever generated modules depend on values produced by
    other generated modules. The implementation is generic: it uses only
    binding source/target module names.
    """

    original_index = {name: index for index, name in enumerate(module_names)}
    remaining = set(module_names)
    deps: dict[str, set[str]] = {name: set() for name in module_names}

    for binding in bindings:
        source = binding.source_module
        target = binding.target_module
        if source in deps and target in deps and source != target:
            deps[target].add(source)

    ordered: list[str] = []

    while remaining:
        ready = [
            name
            for name in remaining
            if not (deps[name] & remaining)
        ]

        if not ready:
            # Cycle or unresolved dependency. Keep deterministic fallback order.
            ready = sorted(remaining, key=lambda name: original_index[name])

        ready.sort(key=lambda name: original_index[name])

        for name in ready:
            if name in remaining:
                ordered.append(name)
                remaining.remove(name)

    return ordered


def build_engine_from_generated_package(
    generated_package_dir: str | Path,
    cif_path: str | Path,
    limit: int | None = None,
    hours: int = 48,
    input_values: dict[str, Any] | None = None,
    engine_name: str = "AutoGeneratedCifPythonEngine",
) -> AutoBuildResult:
    factory = load_generated_factory(generated_package_dir)
    engine = GenericSimulationEngine(engine_name)
    input_values = input_values or {}

    input_module_names: list[str] = []
    if hasattr(factory, "create_input_modules"):
        modules = factory.create_input_modules(**_accepted_input_kwargs(limit, hours, input_values))
        for module in modules.values():
            engine.add_input_module(module)
            input_module_names.append(module.name)

    dynamic_templates = list(getattr(factory, "REGISTRY", {}).keys())
    dynamic_modules_by_name: dict[str, Any] = {}
    dynamic_module_names: list[str] = []

    for template_name in dynamic_templates:
        count = factory.INSTANCE_COUNTS[template_name]
        if limit is not None:
            count = min(count, limit)
        for index in range(count):
            module = factory.create_module(template_name, index)
            dynamic_modules_by_name[module.name] = module
            dynamic_module_names.append(module.name)

    bindings = []
    if dynamic_templates:
        bindings = resolve_bindings_from_file(
            cif_path,
            template_filter=dynamic_templates,
            limit_per_template=limit,
        )

    execution_order = _topological_module_order(dynamic_module_names, bindings)
    for module_name in execution_order:
        engine.add_module(dynamic_modules_by_name[module_name])

    if dynamic_templates:
        apply_cif_bindings(
            engine,
            cif_path=cif_path,
            template_filter=dynamic_templates,
            limit_per_template=limit,
        )

    for input_module_name in input_module_names:
        apply_input_bindings(engine, input_module_name)

    return AutoBuildResult(
        engine=engine,
        factory=factory,
        input_modules=input_module_names,
        dynamic_templates=dynamic_templates,
        dynamic_modules=dynamic_module_names,
        execution_order=execution_order,
    )



def _resolve_event_target(build_result: AutoBuildResult, target: str | None) -> str:
    if target:
        if target in build_result.engine.modules:
            return target

        matching = [
            module_name
            for module_name in build_result.execution_order
            if module_name == target or module_name.startswith(f"{target}_")
        ]
        if len(matching) == 1:
            return matching[0]

        raise ValueError(f"Event target not found or ambiguous: {target}")

    if len(build_result.execution_order) == 1:
        return build_result.execution_order[0]

    raise ValueError(
        "Event target is required when the generated package contains more than one module."
    )


def run_event_trace(
    build_result: AutoBuildResult,
    event_trace: list[EventTraceItem],
    save_every: int = 1,
    strict: bool = True,
) -> dict[str, Any]:
    engine = build_result.engine

    if not event_trace:
        return {
            "mode": "event-trace",
            "events": [],
            "results": engine.get_results(),
        }

    event_history: list[dict[str, Any]] = []

    # Store initial state before the first external event.
    engine._save_results()

    for index, item in enumerate(event_trace):
        module_name = _resolve_event_target(build_result, item.target)
        module = engine.modules[module_name]

        if item.step > engine.current_timestep:
            engine.current_timestep = item.step

        fired = module.fire(item.event) if hasattr(module, "fire") else False
        engine._refresh_module_variables(module_name, module)

        if strict and not fired:
            variables = dict(module.get_variables()) if hasattr(module, "get_variables") else {}
            raise RuntimeError(
                "Event trace requested an event that is not enabled in the current CIF state: "
                f"sample={index + 1}, step={item.step}, target={module_name!r}, "
                f"event={item.event!r}, variables={variables!r}. "
                "This matches ESCET trace-input semantics: a requested event must be consumable; "
                "disabled events are invalid trace items, not silent no-ops."
            )

        if (index + 1) % save_every == 0:
            engine._save_results()

        event_history.append(
            {
                "step": item.step,
                "target": module_name,
                "event": item.event,
                "fired": fired,
                "variables": dict(module.get_variables()),
            }
        )

    return {
        "mode": "event-trace",
        "events": event_history,
        "results": engine.get_results(),
    }


def run_engine_if_possible(
    build_result: AutoBuildResult,
    events: list[str] | None = None,
    event_trace: list[EventTraceItem] | None = None,
    save_every: int = 1,
    strict_event_trace: bool = True,
) -> dict[str, Any]:
    engine = build_result.engine
    events = events or []

    if event_trace is not None:
        return run_event_trace(
            build_result,
            event_trace,
            save_every=save_every,
            strict=strict_event_trace,
        )

    if build_result.input_modules:
        engine.run_till_timestep(-1, save_every=save_every)
        return {
            "mode": "step-driven",
            "steps": engine.current_timestep,
            "results": engine.get_results(),
        }

    event_history = []
    if events and build_result.execution_order:
        module_name = build_result.execution_order[0]
        module = engine.modules[module_name]

        engine._save_results()
        event_history.append({"event": "initial", "fired": True, "variables": dict(module.get_variables())})

        for step_index, event in enumerate(events):
            fired = module.fire(event) if hasattr(module, "fire") else False
            engine.current_timestep = step_index
            engine._refresh_module_variables(module_name, module)
            if not fired:
                variables = dict(module.get_variables()) if hasattr(module, "get_variables") else {}
                raise RuntimeError(
                    "Explicit event requested but not enabled in the current CIF state: "
                    f"sample={step_index + 1}, target={module_name!r}, "
                    f"event={event!r}, variables={variables!r}. "
                    "Disabled events are invalid explicit event inputs, not silent no-ops."
                )
            engine._save_results()
            event_history.append({"event": event, "fired": fired, "variables": dict(module.get_variables())})
        return {
            "mode": "event-driven",
            "events": event_history,
            "results": engine.get_results(),
        }

    return {
        "mode": "not-run",
        "reason": "No input module was generated and no events were supplied.",
    }


def compact_module_summary(engine: GenericSimulationEngine, max_modules: int = 5) -> list[dict[str, Any]]:
    summary: list[dict[str, Any]] = []
    for index, (module_name, module) in enumerate(engine.modules.items()):
        if index >= max_modules:
            break
        variables = dict(module.get_variables())
        summary.append({"module": module_name, "variables": variables})
    return summary
