#!/usr/bin/env python3
from __future__ import annotations

"""
Convert ESCET `.trajdata` files to CSV and optionally collapse them to the
logical sample points generated by `csv_to_escet_trace_grid.py`.

The ESCET trajectory data output always contains `time` and, by default,
additional state/input/algebraic variables of type bool/int/real. This helper
makes those files easier to feed into the behavioral comparison script.
"""

import argparse
import csv
import json
import re
import sys
from pathlib import Path
from typing import Iterable

ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from pipeline.path_defaults import default_validation_dir



def _split_trajdata_line(line: str) -> list[str]:
    stripped = line.strip()
    if not stripped:
        return []
    if "," in stripped and stripped.count(",") >= 1 and "   " not in stripped:
        parts = [part.strip() for part in stripped.split(",")]
    else:
        # ESCET .trajdata is column aligned using runs of spaces. Splitting on any
        # whitespace breaks the first header cell ("# time") into two fake columns.
        parts = [part.strip() for part in re.split(r"\s{2,}", stripped) if part.strip()]

    if parts and parts[0] == "# time":
        parts[0] = "time"
    return parts


def read_trajdata(path: str | Path) -> tuple[list[str], list[list[str]]]:
    path = Path(path)
    lines = [line.rstrip("\n") for line in path.read_text().splitlines() if line.strip()]
    if not lines:
        raise ValueError(f"Empty trajectory data file: {path}")

    header = _split_trajdata_line(lines[0])
    if not header:
        raise ValueError(f"Could not parse trajectory data header: {path}")

    rows: list[list[str]] = []
    for line_index, line in enumerate(lines[1:], start=2):
        parts = _split_trajdata_line(line)
        if not parts:
            continue
        # ESCET may repeat the header block several times in long .trajdata files.
        if parts == header:
            continue
        if len(parts) != len(header):
            raise ValueError(
                f"Trajectory row length mismatch at line {line_index}: "
                f"expected {len(header)} columns, got {len(parts)}"
            )
        rows.append(parts)

    return header, rows


def _load_plan(path: str | Path | None) -> dict | None:
    if path is None:
        return None
    plan_path = Path(path)
    return json.loads(plan_path.read_text())


def _select_columns(header: list[str], rows: list[list[str]], columns: list[str] | None) -> tuple[list[str], list[list[str]]]:
    if not columns:
        return header, rows

    missing = [column for column in columns if column not in header]
    if missing:
        raise ValueError(f"Requested columns not found in trajectory data: {missing}")

    indexes = [header.index(column) for column in columns]
    filtered_rows = [[row[index] for index in indexes] for row in rows]
    return columns, filtered_rows


def _sample_rows_by_plan(header: list[str], rows: list[list[str]], plan: dict) -> tuple[list[list[str]], list[int]]:
    sample_row_indexes = plan.get("sample_row_indexes")
    if isinstance(sample_row_indexes, list) and sample_row_indexes:
        normalized = [int(v) for v in sample_row_indexes]
        if all(0 <= idx < len(rows) for idx in normalized):
            return [rows[idx] for idx in normalized], normalized

    if "time" not in header:
        raise ValueError(
            "Trace plan row indexes do not match the trajectory data, and there is no 'time' column available for fallback sampling."
        )

    logical_steps = plan.get("logical_steps")
    if not isinstance(logical_steps, list) or not logical_steps:
        raise ValueError(
            "Trace plan row indexes do not match the trajectory data, and the plan has no 'logical_steps' for time-based fallback sampling."
        )

    time_idx = header.index("time")
    time_values = [float(row[time_idx]) for row in rows]
    tolerance = 1e-6

    selected_indexes: list[int] = []
    selected_rows: list[list[str]] = []
    for step in logical_steps:
        logical_step = step.get("logical_step")
        target_time = 0.0 if logical_step is None else float(logical_step)
        candidates = [i for i, value in enumerate(time_values) if value <= target_time + tolerance]
        if candidates:
            chosen = candidates[-1]
        else:
            chosen = min(range(len(time_values)), key=lambda i: abs(time_values[i] - target_time))
        selected_indexes.append(chosen)
        selected_rows.append(rows[chosen])

    return selected_rows, selected_indexes


def _write_csv(path: str | Path, header: list[str], rows: Iterable[list[str]]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert ESCET .trajdata output to CSV and optionally sample logical step boundaries."
    )
    parser.add_argument('--trajdata', default=None, help='ESCET trajectory data file')
    parser.add_argument("--output-csv", default=None, help="CSV file to write")
    parser.add_argument(
        "--trace-plan",
        default=None,
        help="Optional JSON sidecar produced by csv_to_escet_trace_grid.py. Use '' to disable logical-step sampling.",
    )
    parser.add_argument(
        "--columns",
        nargs="*",
        default=None,
        help="Optional explicit column filter, e.g. time Rad Nodes_0.N LAI_0.lai Biomass_0.w",
    )
    parser.add_argument(
        "--raw-copy",
        action="store_true",
        help="Ignore the trace plan and just convert the full trajectory data file to CSV.",
    )
    args = parser.parse_args()

    trace_plan = None if (args.raw_copy or args.trace_plan == "") else _load_plan(args.trace_plan)
    if args.trajdata:
        trajdata_path = Path(args.trajdata)
    elif args.trace_plan:
        plan_hint = json.loads(Path(args.trace_plan).read_text())
        model_name = Path(plan_hint.get('cif', 'ad_hoc')).stem
        trajdata_path = default_validation_dir(model_name=model_name, project_root=ROOT_DIR) / 'escet_grid' / f'{model_name}.trajdata'
    else:
        raise ValueError('Provide --trajdata or --trace-plan to infer the model-specific default paths.')

    if args.trace_plan:
        trace_plan_path = Path(args.trace_plan)
    else:
        model_name = trajdata_path.stem
        trace_plan_path = default_validation_dir(model_name=model_name, project_root=ROOT_DIR) / 'escet_grid' / f'{model_name}.trace.plan.json'

    output_csv_path = Path(args.output_csv) if args.output_csv else (trajdata_path.parent / f'{trajdata_path.stem}_escet_trace.csv')

    header, rows = read_trajdata(trajdata_path)

    sampled_indexes: list[int] | None = None
    if trace_plan is not None:
        rows, sampled_indexes = _sample_rows_by_plan(header, rows, trace_plan)

    header, rows = _select_columns(header, rows, args.columns)
    _write_csv(output_csv_path, header, rows)

    print(f"ESCET CSV: {output_csv_path}")
    print(f"data rows written: {len(rows)}")
    if sampled_indexes is not None:
        print(f"sampled trajectory row indexes: {sampled_indexes[:10]}{'...' if len(sampled_indexes) > 10 else ''}")


if __name__ == "__main__":
    main()
